### ISSUE TITLE
Address integrator issue (Cross database associations)

### ISSUE THREAD

**Issue by devinivy** [balderdashy/waterline#925]
A potential issue with the integrator was brought-up by @particlebanana in https://github.com/balderdashy/waterline/issues/664#issuecomment-57248273 , issue #664.  This is a technical issue that needs review and a potential fix.  If @particlebanana could chime-in what exactly to look for, that would be very useful!

**Pending tasks:**
- [x] 1. PR #984 merged
- [x] 2. PR #985: unit tests may need to be revised 
- [x] 3. PR balderdashy/sails-mysql#212 merged
- [x] 4. PR balderdashy/sails-postgresql#158 merged
- [ ] 5. balderdashy/waterline-adapter-tests#64
  - [x] Enable cross-adapter tests in sails-mongo balderdashy/sails-mongo#282
  - [x] Enable cross-adapter tests in sails-memory balderdashy/sails-memory#22
  - [x] Enable cross-adapter tests in sails-disk balderdashy/sails-disk#43
  - [x] Enable cross-adapter tests in sails-mysql balderdashy/sails-mysql#221
  - [x] Enable cross-adapter tests in sails-postgresql balderdashy/sails-postgresql#160
- [x] 6. Fix Populate m:m cross adapter/connection issue #1014

**Comment by dmarcelino** [comment]
Could also fix:
* Association .populate() only populates defined attributes #366
* weird results in populated data #503
* Join failing across adapters #833

Possible solution, PR: Allow Associations to Use 'type' as a Name #789

**Comment by devinivy** [comment]
@particlebanana do you have a moment to provide some insight as to general integrator issues to look into?

**Comment by dmarcelino** [comment]
Hey @devinivy, @particlebanana, I have good news and bad news:
* The good news are I've managed to create a comprehensive test suite for associations across multiple connections (same adapter) by re-using the existing associations tests: https://github.com/balderdashy/waterline-adapter-tests/commit/dc7c871377b2a6e2c89f1719c9675309cf966c6e
* The bad news is that a lot of tests are breaking. Even for sails-memory which passes more tests it's breaking 26 and passes 40. Most breaking tests are nested operations: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/60035080#L937

Let me know what you think.

**Comment by dmarcelino** [comment]
PR #848, makes 8 additional cross db tests pass, can you guys take a look?

**Comment by dmarcelino** [comment]
@devinivy, @particlebanana, I've made a PR with the cross adapter tests: balderdashy/waterline-adapter-tests#57, please.

**Comment by particlebanana** [comment]
Ok guys #984 solves all of these but two at least in my testing. I recreated the projects in the issues @dmarcelino linked to and they seemed to be solved. All tests are passing with the newer cross adapter tests.

#619 is solved by the update to [waterline-sequel](https://github.com/balderdashy/waterline-sequel/pull/46) and the two open pr's for [sails-mysql](https://github.com/balderdashy/sails-mysql/pull/212) and [sails-postgresql](https://github.com/balderdashy/sails-postgresql/pull/158). It's a breaking change so sql adapters will need to be tweaked if they want to upgrade to the latest wl-sql.

#336 still needs to be fixed. It's a simple integrator problem I'll try and get knocked out asap.

**Comment by particlebanana** [comment]
Ok I just submitted https://github.com/balderdashy/waterline/pull/985 that might fix #366

**Comment by dmarcelino** [comment]
Impressive work, great turn around, I'm truly impressed by this! :smiley: :clap:

Tomorrow I'll take a look the SQL PRs.

**Comment by dmarcelino** [comment]
Here's my outline regarding all the awesome work @particlebanana has done:
* PR #984 looks great! :white_check_mark: 
* PR #985, unit tests may need to be revised :warning: 
* PR balderdashy/sails-mysql#212 looks good :white_check_mark: 
* PR balderdashy/sails-postgresql#158 looks good :white_check_mark: 
* PR balderdashy/waterline-adapter-tests#62 not DRY and in its current form can break tests for adapters that don't (yet) support cross-adapter tests. Please take a look at balderdashy/waterline-adapter-tests#64 :warning:

**Comment by dmarcelino** [comment]
@devinivy, @particlebanana: ping :bell: 

Guys, it would be great to get to the bottom of the things I've mentioned on my last comment and release new versions!

**Comment by devinivy** [comment]
Just checking-in, clarifying what's to be done.  Looking at the [comment above](https://github.com/balderdashy/waterline/issues/925#issuecomment-98353381)...

Point 2 (#985) needs some more work/clarification from @particlebanana .  I'm going to take a closer look at it soon.

Point 3 and 4 may be resolved, pending this PR to @particlebanana's branch: https://github.com/particlebanana/sails-mysql/pull/1

Does point 5 rely on non-existent PRs on the official adapters?

**Comment by dmarcelino** [comment]
Regarding 5. you could say there are 2 or 3 questions to be answered:
* do we go for balderdashy/waterline-adapter-tests#62 or balderdashy/waterline-adapter-tests#64? My opinion is 64.
  * if we choose **62**, anything needs to be done? I believe it only depends on PR #984 but not 100% sure.
  * **64:** We will need to add `"waterlineAdapter": { "features": ["cross-adapter"] }` to every official adapter and of course merge PR #984 otherwise the tests break.

**Comment by dmarcelino** [comment]
Status update:
- [ ] 1. 
- [ ] 1. 
- [ ] 1. 
- [ ] 1.
